// <auto-generated />
namespace WS.Database.Bootstrap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-beta2-31111")]
    public sealed partial class Update_ProductCategoryManufacturerRelationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_ProductCategoryManufacturerRelationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201501021430069_Update_ProductCategoryManufacturerRelationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
