// <auto-generated />
namespace WS.Database.Bootstrap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-beta2-31111")]
    public sealed partial class Category_ParentSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_ParentSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201511302056250_Category_ParentSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
